/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class qio_uring_Lib */

#ifndef _Included_qio_uring_Lib
#define _Included_qio_uring_Lib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     qio_uring_Lib
 * Method:    openFile
 * Signature: ([BII)J
 */
JNIEXPORT jlong JNICALL Java_qio_uring_Lib_openFile
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     qio_uring_Lib
 * Method:    closeFile
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_qio_uring_Lib_closeFile
  (JNIEnv *, jobject, jint);

/*
 * Class:     qio_uring_Lib
 * Method:    openSocket
 * Signature: ([BIIII[I)J
 */
JNIEXPORT jlong JNICALL Java_qio_uring_Lib_openSocket
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint, jintArray);

/*
 * Class:     qio_uring_Lib
 * Method:    closeSocket
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_qio_uring_Lib_closeSocket
  (JNIEnv *, jobject, jint);

/*
 * Class:     qio_uring_Lib
 * Method:    openEPoll
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_qio_uring_Lib_openEPoll
  (JNIEnv *, jobject, jint);

/*
 * Class:     qio_uring_Lib
 * Method:    closeEPoll
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_qio_uring_Lib_closeEPoll
  (JNIEnv *, jobject, jint);

/*
 * Class:     qio_uring_Lib
 * Method:    allocBuffer
 * Signature: (I[Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_qio_uring_Lib_allocBuffer
  (JNIEnv *, jobject, jint, jobjectArray);

/*
 * Class:     qio_uring_Lib
 * Method:    freeBuffer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_qio_uring_Lib_freeBuffer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     qio_uring_Lib
 * Method:    strError
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_qio_uring_Lib_strError
  (JNIEnv *, jobject, jint);

/*
 * Class:     qio_uring_Lib
 * Method:    probe
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_qio_uring_Lib_probe
  (JNIEnv *, jobject);

/*
 * Class:     qio_uring_Lib
 * Method:    setup
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_qio_uring_Lib_setup
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     qio_uring_Lib
 * Method:    shutdown
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_qio_uring_Lib_shutdown
  (JNIEnv *, jobject, jlong);

/*
 * Class:     qio_uring_Lib
 * Method:    post
 * Signature: (J[Lqio/uring/RQE;)I
 */
JNIEXPORT jint JNICALL Java_qio_uring_Lib_post
  (JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     qio_uring_Lib
 * Method:    poll
 * Signature: (J[Lqio/uring/RQE;)I
 */
JNIEXPORT jint JNICALL Java_qio_uring_Lib_poll
  (JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     qio_uring_Lib
 * Method:    take
 * Signature: (J[Lqio/uring/RQE;IJ)I
 */
JNIEXPORT jint JNICALL Java_qio_uring_Lib_take
  (JNIEnv *, jobject, jlong, jobjectArray, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
